In [1]:
#Source : https://github.com/PacktPublishing/Python-Natural-Language-Processing-Cookbook-Second-Edition/tree/main/data

# Bag-of-words

In [2]:
# -*- coding: utf-8 -*-
"""3.1_simple_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u5qNyCdnXTy55u301cNWXe2mVa9Jjx7W

# Simple classifier
"""

# !python -m spacy download en_core_web_lg
import nltk
import spacy
from nltk import word_tokenize
from nltk.corpus import stopwords
from string import punctuation
small_model = spacy.load("en_core_web_sm")
large_model = spacy.load("en_core_web_lg")

from datasets import load_dataset
train_dataset = load_dataset("rotten_tomatoes", split="train[:15%]+train[-15%:]")
test_dataset = load_dataset("rotten_tomatoes", split="test[:15%]+test[-15%:]")

print(len(train_dataset))
print(len(test_dataset))

class POS_vectorizer:
    def __init__(self, spacy_model):
        self.model = spacy_model

    def vectorize(self, input_text):
        doc = self.model(input_text)
        vector = []
        vector.append(len(doc))
        pos = {"VERB":0, "NOUN":0, "PROPN":0, "ADJ":0, "ADV":0, "AUX":0, "PRON":0, "NUM":0, "PUNCT":0}
        for token in doc:
            if token.pos_ in pos.keys():
                pos[token.pos_] += 1
        vector_values = list(pos.values())
        vector = vector + vector_values
        return vector

sample_text = train_dataset[0]["text"]
vectorizer = POS_vectorizer(small_model)
vector = vectorizer.vectorize(sample_text)

print(sample_text)
print(vector)

import pandas as pd
import numpy as np
train_df = train_dataset.to_pandas()
train_df.sample(frac=1)
test_df = test_dataset.to_pandas()
train_df["vector"] = train_df["text"].apply(lambda x: vectorizer.vectorize(x))
test_df["vector"] = test_df["text"].apply(lambda x: vectorizer.vectorize(x))
X_train = np.stack(train_df["vector"].values, axis=0)
X_test = np.stack(test_df["vector"].values, axis=0)
y_train = train_df["label"].to_numpy()
y_test = test_df["label"].to_numpy()

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
clf = LogisticRegression(C=0.1)
clf = clf.fit(X_train, y_train)

test_df["prediction"] = test_df["vector"].apply(lambda x: clf.predict([x])[0])
print(classification_report(test_df["label"], test_df["prediction"]))

/Users/lwhitenack/CS-620/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


2560
320
the rock is destined to be the 21st century's new " conan " and that he's going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .
[38, 3, 8, 2, 5, 1, 3, 1, 0, 5]
              precision    recall  f1-score   support

           0       0.58      0.56      0.57       160
           1       0.58      0.59      0.58       160

    accuracy                           0.58       320
   macro avg       0.58      0.58      0.58       320
weighted avg       0.58      0.58      0.58       320



/Users/lwhitenack/CS-620/.venv/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/lwhitenack/CS-620/.venv/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/lwhitenack/CS-620/.venv/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/lwhitenack/CS-620/.venv/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: divide by zero encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/Users/lwhitenack/CS-620/.venv/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: overflow encountered in matmul
  grad[:n_features] = X.T @ grad_point

In [3]:

from sklearn.feature_extraction.text import CountVectorizer
import sys

In [4]:
(train_df, test_df) = load_train_test_dataset_pd()

NameError: name 'load_train_test_dataset_pd' is not defined

In [ ]:
vectorizer = CountVectorizer(max_df=0.4)
X = vectorizer.fit_transform(train_df["text"])
print(X)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 39134 stored elements and shape (2560, 8856)>
  Coords	Values
  (0, 6578)	1
  (0, 4219)	1
  (0, 2106)	1
  (0, 8000)	2
  (0, 717)	1
  (0, 42)	1
  (0, 1280)	1
  (0, 5260)	1
  (0, 1607)	1
  (0, 7889)	1
  (0, 3630)	1
  (0, 3406)	1
  (0, 4759)	1
  (0, 7345)	1
  (0, 2707)	1
  (0, 3476)	1
  (0, 7883)	1
  (0, 487)	1
  (0, 6769)	1
  (0, 4269)	1
  (0, 1441)	1
  (0, 8405)	1
  (0, 1889)	1
  (0, 5466)	1
  (0, 7461)	1
  :	:
  (2557, 5905)	1
  (2557, 3595)	1
  (2557, 6745)	1
  (2557, 1023)	1
  (2557, 5259)	1
  (2558, 8000)	1
  (2558, 5331)	1
  (2558, 6733)	1
  (2558, 970)	1
  (2558, 4150)	1
  (2558, 874)	1
  (2559, 4219)	1
  (2559, 5128)	1
  (2559, 285)	1
  (2559, 5292)	1
  (2559, 6278)	1
  (2559, 5326)	1
  (2559, 7929)	1
  (2559, 3336)	1
  (2559, 5622)	1
  (2559, 6748)	1
  (2559, 8629)	1
  (2559, 7915)	1
  (2559, 1679)	1
  (2559, 5904)	1


In [ ]:
dense_matrix = X.todense()
print(dense_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
print(vectorizer.get_feature_names_out())
print(len(vectorizer.get_feature_names_out()))

['10' '100' '101' ... 'zone' 'ótimo' 'últimos']
8856


In [ ]:
print(vectorizer.get_stop_words())

None


In [ ]:
first_review = test_df['text'].iat[0]
print(first_review)

lovingly photographed in the manner of a golden book sprung to life , stuart little 2 manages sweetness largely without stickiness .


In [ ]:
sparse_vector = vectorizer.transform([first_review])
print(sparse_vector)
dense_vector = sparse_vector.todense()
np.set_printoptions(threshold=sys.maxsize)
print(dense_vector)
np.set_printoptions(threshold=False)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 13 stored elements and shape (1, 8856)>
  Coords	Values
  (0, 955)	1
  (0, 3968)	1
  (0, 4451)	1
  (0, 4562)	1
  (0, 4622)	1
  (0, 4688)	1
  (0, 4779)	1
  (0, 4792)	1
  (0, 5764)	1
  (0, 7547)	1
  (0, 7715)	1
  (0, 8000)	1
  (0, 8734)	1
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

None


In [ ]:
vectorizer = CountVectorizer(max_df=300)
X = vectorizer.fit_transform(train_df["text"])
print(vectorizer.stop_words_)

AttributeError: 'CountVectorizer' object has no attribute 'stop_words_'

In [ ]:
vectorizer = CountVectorizer(stop_words=['the', 'this', 'these', 'in', 'at', 'for'])
X = vectorizer.fit_transform(train_df["text"])

In [ ]:
from sklearn.metrics import classification_report
import numpy as np

def test_classifier(test_df, clf, vectorizer):
    vectorize = lambda x: vectorizer.transform([x]).toarray()[0]
    test_df["prediction"] = test_df["text"].apply(lambda x: clf.predict([vectorize(x)])[0])
    print(classification_report(test_df["label"], test_df["prediction"]))

In [ ]:
vectorizer = CountVectorizer(max_df=300)
(train_df, test_df) = load_train_test_dataset_pd()
X = vectorizer.fit_transform(train_df["text"])
vectorize = lambda x: vectorizer.transform([x]).toarray()[0]
(X_train, X_test, y_train, y_test) = create_train_test_data(train_df, test_df, vectorize)
clf = train_classifier(X_train, y_train)
test_classifier(test_df, clf, vectorizer)

              precision    recall  f1-score   support

           0       0.74      0.69      0.72       160
           1       0.71      0.76      0.74       160

    accuracy                           0.73       320
   macro avg       0.73      0.73      0.73       320
weighted avg       0.73      0.73      0.73       320



Sample Sentence: This is a sample sentence for bag of words.
Bag-of-Words Vector (Sparse): <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (1, 8842)>
  Coords	Values
  (0, 643)	1
  (0, 6865)	1
  (0, 8748)	1
Bag-of-Words Vector (Dense): [[0 0 0 ... 0 0 0]]
